### ISSUE TITLE
Can’t find localssh in Chariz repo

### ISSUE THREAD

**Issue by santhoshkumar5067** [demhademha/tweak-development-guide#1]
Am following your tweak development program and am stuck in lesson 1. Cant find localssh in Chariz repo…

**Comment by halvis82** [comment]
I had that problem too. It's in https://halo-michael.github.io/repo

**Comment by santhoshkumar5067** [comment]
Great! It worked… thank you

**Comment by demhademha** [comment]
Fixed in https://github.com/demhademha/tweak-development-guide/commit/58b5a83fbf2d076ad23d323f5c5015c5a63a4131
Have. A great day
