### ISSUE TITLE
.profile in "/var/mobile" or "/var/root" ?

### ISSUE THREAD

**Issue by PaulProjects** [demhademha/tweak-development-guide#21]
[Chapter 4](https://github.com/demhademha/tweak-development-guide/blob/master/chapter-4.md) tells me:

> Now, open Filza and navigate to /var/mobile, you should see .profile (for bash) or .zprofile (for zsh), and open the correct file according to your shell. However, if the file isn't displayed, you'll need to manually create the .profile or the .zprofile file yourself. 

I followed the text and created that file. 
As `echo $SDKROOT` in Chapter 5 did not work for me, I tested a bit around. I copied the file to "/var/root" and it works now.
Before that I changed the terminal too bash (https://github.com/demhademha/tweak-development-guide/issues/8#issuecomment-712628481).

btw nice guide

**Comment by Silverethical** [comment]
> [Chapter 4](https://github.com/demhademha/tweak-development-guide/blob/master/chapter-4.md) tells me:
> 
> > Now, open Filza and navigate to /var/mobile, you should see .profile (for bash) or .zprofile (for zsh), and open the correct file according to your shell. However, if the file isn't displayed, you'll need to manually create the .profile or the .zprofile file yourself.
> 
> I followed the text and created that file.
> As `echo $SDKROOT` in Chapter 5 did not work for me, I tested a bit around. I copied the file to "/var/root" and it works now.
> Before that I changed the terminal too bash ([#8 (comment)](https://github.com/demhademha/tweak-development-guide/issues/8#issuecomment-712628481)).
> 
> btw nice guide

I think you are SSHing as root, which you should not do. Always SSH as mobile unless told otherwise. (replace `root` with `mobile` in SSH command)

**Comment by demhademha** [comment]
Chapter 4 assumes you're logging in as the **mobile** user, subsequently, the profile is only created for that user. When logging in over ssh, you should login as the **mobile** user

**Comment by PaulProjects** [comment]
Oh misread that thank you
