### ISSUE TITLE
zsh:killed      ./my-first-program

### ISSUE THREAD

**Issue by k3v1nwrld** [demhademha/tweak-development-guide#27]
On chapter 6 program 6.1 whenever i run ./my-first-program i get:
zsh:killed      ./my-first-program
![test](https://user-images.githubusercontent.com/75213647/129783717-37076846-f42c-4e56-a657-93cc79c13fdd.png)

**Comment by demhademha** [comment]
This is a jailbreak issue.
although procursus **would** automatically sign binaries, this is no longer the case.
in order to overcome this issue, you can do either the following:
• use ldid to sign your binary 
• create a /home directory and  build everything from within there.

**Comment by k3v1nwrld** [comment]
I tried to sign with ldid by running ldid -S my-first-program but it didnt help.I think im doing something wrong and tried to google it but didnt find anything.

**Comment by demhademha** [comment]
1: download this file https://github.com/ProcursusTeam/Procursus/blob/main/build_misc/entitlements/general.xml (using either wget or curl)
2: do, `ldid -Sgeneral.xml my-first-program`
3: try to run the program again 
Let me know if this works

**Comment by k3v1nwrld** [comment]
Downloaded the file at /var/mobile and moved it to /tmp too but still get an error
![ldid](https://user-images.githubusercontent.com/75213647/131866531-61a5bbc6-a95e-43fc-857f-d5cd9aacc9ef.png)

**Comment by demhademha** [comment]
Could you sign and run the file in the same directory - IE, build it in /var/mobile and run it in /var/mobile (without moving it to /tmp)
regards

**Comment by k3v1nwrld** [comment]
Still get the same thing.When i used chrckra1n with procursus this worked completely fine but since i switched to taurine it requires to sign it with ldid

**Comment by demhademha** [comment]
try this: 
1: `sudo mkdir /home/username`
2: `sudo chown mobile:mobile /home/username`
3: try to compile in that directory (`/home/useranme`)  
CC @diatrus - can we have the ldid auto signer back...

**Comment by k3v1nwrld** [comment]
When i run sudo mkdir /home/test i get
Mkdir: cannotcreate directory '/home/test':No such file or directory

**Comment by demhademha** [comment]
Sorry, use `sudo mkdir -p /home/username`

**Comment by k3v1nwrld** [comment]
Thanks it works now!
